FROM alpine:latest
WORKDIR /app

# Install required dependencies
RUN apk add --no-cache ca-certificates

# Copy your PocketBase binary into the container
COPY pocketbase /app/pocketbase

# Make it executable
RUN chmod +x /app/pocketbase

# Run PocketBase
CMD ["./pocketbase", "serve", "--http", "0.0.0.0:10000"]
